#!/bin/bash

# output a system info page

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

function report_uptime() {
    #cat <<- _EOF_
    #        <H2>System Uptime</H2>
    #        <PRE>$(uptime)</PRE>
    #        _EOF_
    echo "  <H2>System Uptime</H2>
            <PRE>$(uptime)</PRE>"
    return
}

function report_disk_space() {
    echo "  <H2>Disk Space Utilization</H2>
            <PRE>$(df -h)</PRE>"
    return
}

function report_home_space() {
    echo "  <H2>Home Space Utilization</H2>
            <PRE>$(du -sh /home/)</PRE>" 
    return
}

echo "<HTML>
          <HEAD>
            <TITLE>$TITLE</TITLE>
          </HEAD>
          <BODY>
            <H1>$TITLE</H1>
            <P>$TIMESTAMP</P>
            $(report_uptime)
            $(report_disk_space)
            $(report_home_space)
         </BODY>
     </HTML>"

